# Generated by Django 5.0.4 on 2025-03-27 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='api.customer'),
            preserve_default=False,
        ),
    ]
